server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Configuration files will be loaded from a local directory named config-repo
          search-locations: file:../config-repo

# Disable eureka client for the config server to avoid circular dependencies at startup
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
