server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # We don't want the registry itself to register with another registry
    registerWithEureka: false
    # Registry doesn't need to fetch registry from itself
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
